name: kv_design_system
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 1.1.6
  analyzer: any
  cached_network_image: any
  diacritic: any
  google_fonts: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  dart_code_metrics_presets: any
  dart_code_metrics: any

flutter:
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom-icons.ttf

    - family: FaBrands400
      fonts:
        - asset: assets/fonts/fa-brands-400.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-Black.ttf
          style: normal